# src/main/resources/application.yml

server:
  port: 8080 # Port aplikasi backend

spring:
  application:
    name: taranium-certs-backend
  # Konfigurasi H2 Database (in-memory)
  datasource:
    url: jdbc:h2:mem:taraniumcertsdb # URL database H2 in-memory
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect # Dialek Hibernate untuk H2
    hibernate:
      ddl-auto: update # Otomatis update skema database
    show-sql: true # Tampilkan query SQL di konsol (untuk debug)

  web:
    cors:
      allowed-origins: http://localhost:3000,http://127.0.0.1:3000,http://localhost:5173 # Izinkan dari port frontend Anda
      allowed-methods: GET,POST,PUT,DELETE,OPTIONS # Metode yang diizinkan
      allowed-headers: "*" # Header yang diizinkan
      allow-credentials: true # Penting untuk mengirim cookie sesi (jika browser mengirimnya, walau tidak akan dipakai lagi)

# Konfigurasi aplikasi kustom
app:
  upload-dir: ./uploads # Direktori untuk menyimpan file yang diupload
